### ISSUE TITLE
Script errors with Ubuntu 14.04 (bash 4.3.11)

### ISSUE THREAD

**Issue by sofakng** [Red5d/pushbullet-bash#12]
I'm getting some bash scripting errors when running this pushbullet script.

For example:
"pushbullet list" corrects returns my devices but then it displays the pushbullet help text followed by:

/usr/local/src/pushbullet-bash/pushbullet: line 157: syntax error near unexpected token `;;'
/usr/local/src/pushbullet-bash/pushbullet: line 157: `;;'

Another example:
"pushbullet push "Nexus 5" note Testing" corrects sends a push notification but it displays this:

grep: 5: No such file or directory
/usr/local/src/pushbullet-bash/pushbullet: line 90: [: too many arguments
created

followed by the pushbullet help text, and then:

/usr/local/src/pushbullet-bash/pushbullet: line 157: syntax error near unexpected token `;;'
/usr/local/src/pushbullet-bash/pushbullet: line 157: `;;'

**Comment by Red5d** [comment]
Fixed in #18
