### ISSUE TITLE
Push to email or channel

### ISSUE THREAD

**Issue by Fullmono** [Red5d/pushbullet-bash#20]
Hi,

Just a little improvement: we are currently able to send pushes to our own devices.
It could be great to be able to send to a channel (when you are owner) or friends.

**Comment by eschava** [comment]
I've created a small patch to send to email if device name contains @ char:

--- a/pushbullet
+++ b/pushbullet
@@ -132,6 +132,8 @@ push)
                fi
                if [ "$2" = "all" ]; then
                        curlres=$(curl -s "$API_URL/pushes" -u "$API_KEY": -d type=note -d title="$4" --data-urlencode body="$body" -X POST)
+               elif [[ "$2" == *"@"* ]]; then
+                       curlres=$(curl -s "$API_URL/pushes" -u "$API_KEY": -d email="$2" -d type=note -d title="$4" --data-urlencode body="$body" -X POST)
                else
                        curlres=$(curl -s "$API_URL/pushes" -u "$API_KEY": -d device_iden="$dev_id" -d type=note -d title="$4" --data-urlencode body="$body" -X POST)
                fi

**Comment by fbartels** [comment]
Hi, your patch did not quite work for me. I had to change the elif to *@* instead of "@".

**Comment by eschava** [comment]
Sorry
it seems parser removed several chars from my patch. Original version was:
```bash
+               elif [[ "$2" == *"@"* ]]; then
+                       curlres=$(curl -s "$API_URL/pushes" -u "$API_KEY": -d email="$2" -d type=note -d title="$4" --data-urlencode body="$body" -X POST)
```

**Comment by fbartels** [comment]
#40 implements pushing of notes to channels
