### ISSUE TITLE
Feature request - allow using editable device alias names instead of names assigned by Pushbullet

### ISSUE THREAD

**Issue by frederickjh** [Red5d/pushbullet-bash#28]
Hi!
I installed a program today on Ubuntu called <b>Pushbullet Indicator</b> and when I set it up and gave it a nice alias in the box which showed up on pushbullet.com. 
![pushbullet_devices_list](https://cloud.githubusercontent.com/assets/864159/6713812/0d065620-cd95-11e4-856c-6949aa701f9e.png)
However, pushbullet assigned it the name: <b>Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty</b> and when i do:
<pre>$ pushbullet list</pre>
this is the name that I get for the device and not the nice alias that I assigned it.

![pushbullet_for_bash_devices_list](https://cloud.githubusercontent.com/assets/864159/6713808/072649ae-cd95-11e4-9afe-2fc6efe23e71.png)

Now I realize that this may open a can of worms as the aliases can change, but users should know when they change their device's aliases. The other thought was how to handle aliases with spaces in them.

Thanks for considering this feature request!

Frederick

**Comment by Red5d** [comment]
I'll certainly consider this and see if I can figure a good way to do it. However, in the meantime, you can actually use a unique part of the device name and not the whole thing if you want. Example: you could use "Linux", "Ubuntu", "trusty", or similar to send to that "Linux-3.13...." device.

**Comment by frederickjh** [comment]
Good to know. Thanks for the tip!

**Comment by fbartels** [comment]
Hi @frederickjh, are you sure you are on the latest version of pushbullet-bash?
![pushbullet-nickname](https://cloud.githubusercontent.com/assets/1257835/6725611/290d7e62-ce0c-11e4-8242-5a0d9797f593.png)

**Comment by frederickjh** [comment]
@fbartels No,  I was  not.  The size of the one I had was 3.8k and the current version is 7.8k. My have you have you grown pushbullet-bash! ;)

Just updated and my list of devices now looks like this:
![pushbullet_list-on_current_version](https://cloud.githubusercontent.com/assets/864159/6740892/b342e3fc-ce83-11e4-9089-a85bea9f08c1.png)
Good catch fbartels!

Now I can send pushes to frederick or book and the all end up at my laptop. So, that all said I am closing this as it looks like this is already in pushbulllet-bash.
