### ISSUE TITLE
Pushing list with only 1 item

### ISSUE THREAD

**Issue by miwie** [Red5d/pushbullet-bash#4]
... like e.g.

pushbullet push device list test bar

results in a list on the device with *3* items (one for every character in the pushed item:

test
o  b
o  a
o  r

Because the assembled curl command looks good (to me) might be an API problem:

curl -s https://www.pushbullet.com/api/pushes -u API_KEY: -d device_id=ID -d type=list -d title=test -d items=foo

**Comment by fbartels** [comment]
This should be obsolete with #24
