### ISSUE TITLE
Notes in PB don't have new lines

### ISSUE THREAD

**Issue by spxxxk** [Red5d/pushbullet-bash#54]
Changing line 161 `	body="${body//$'\n'/\n}"` to `	body="${body//$'\n'/\\n}"` fixes it for me.

**Comment by fbartels** [comment]
Hi,

I could verify your problem when piping files containing new lines to pushbullet-bash. I added your proposed fix and made a pull request in #55

**Comment by Red5d** [comment]
Fixed in #55
