### ISSUE TITLE
Issues with line breaks inside note variables?

### ISSUE THREAD

**Issue by theCheek** [Red5d/pushbullet-bash#76]
Hi, great work to all contributors.
Having an issue with line breaks when inside a bash variable. Seems to throw an error:
Error submitting the request. The error message was: {"error":

> {"code":"invalid_request","type":"invalid_request","message":"Failed tecode JSON body.","cat":"(=^‥^=)"},"error_code":"invalid_request"}

**Comment by Red5d** [comment]
Thanks, can you give an example command/message that replicates this error?

**Comment by theCheek** [comment]
sure! I'm trying to get bash script to delete the oldest files in a directory until a certain diskspace percentage is reached. With each loop the file that was just deleted is added to a variable, but with a break in the line. At the end of the process, I wanted a summary of all files that were deleted to be sent to pushbullet. When echoing the variable, its got the line breaks, and looks pretty, but no luck so far with the pushbullet. If I remove the line break in the variable deletedFiles then pushbullet receives the note just fine.

Apologies for my script kiddyness, i'm pretty new to all this!

```
process_file () {
    
    FILE="$1"

    echo "Deleting oldest file $FILE"
	deletedFiles+="$FILE 
"
    rm -f "$FILE"

}
send_summary(){
       echo "The following files have been deleted to make space: $deletedFiles . 
       ~/scripts/pushbullet-bash/pushbullet push familyseedbox note "The following files have been deleted to make space: $deletedFiles ."
}
        
```

**Comment by Red5d** [comment]
Ok, apparently doing line breaks "like
this
"
uses a hex character or something and I haven't been able to get replacing it to an actual \n newline to work yet. However, I would suggest adjusting your script to append "$FILE\n" to the deletedFiles variable instead of the line break. the "\n" newlines seem to show up correctly in Pushbullet.

**Comment by theCheek** [comment]
Perfect! Works like a charm thanks!
