### ISSUE TITLE
problem-specific error codes?

### ISSUE THREAD

**Issue by r2evans** [Red5d/pushbullet-bash#81]
For discussion: what are your thoughts on returning different error codes? For instance, I can see utility in differentiating between hard and transient errors. I could loop on sending a message until success. If the send is failing because of a config problem, then it will never succeed (and loop needlessly).

I don't mind working on a PR for it, just wanted to know your (@Red5d's) opinion before going down this road. If generally "yes", could you help enumerate what error codes would make sense?

* 1-99: return codes passed through from `curl` (e.g., 6 is "couldn't resolve host", 7 is "failed to connect to host", both possibly transient errors)
* 200: PB authentication error
* 201: PB device error (not found or already exists?)
* 202: PB object-not-found error
* 203: PB other error
* 210: dependency error (hard fail)
* 211: configuration error
* 212: URL or email format error
* 213: file error (perms or not found)
 
Since the current method is to always return "1" if there's an error, I don't see backward compatibility being an issue here. Since `man curl` only lists up to 90 at the moment, it should be easy to start at 100; I chose 200 only to preserve plenty of room for curl's error-code expansion.

**Comment by fbartels** [comment]
Thanks for your pull request, this has now been merged.

**Comment by fbartels** [comment]
On a related note. in #82 you gave the following snippet:

```
MSG="hello world, my external IP changed to ${WANIP}"
./pushbullet push mydev note "${MSG}"
retcode=$?
while [ "$retcode" = "5" -o "$retcode" = "6" -o "$retcode" = "7" ]; do
    sleep 300
    ./pushbullet push mydev note "${MSG}"
    retcode=$?
done
```

What would you think if such an error handling would be directly included in pushbullet-bash? e.g. if curl gives a network error retry for a given amount of times before failing. this given amount could be configurable as well imho.

**Comment by r2evans** [comment]
I had considered it, but didn't want to get too far ahead of myself with regards to suggested-changes.

Perhaps along the lines of:

```diff
 printUsage() {
-echo "Usage: pushbullet [-q|--quiet|-d|--debug] <action> <device> <type> <data>
+echo "Usage: pushbullet [-q|--quiet|-d|--debug|-R [-E...|-D...|-T...] ] <action> <device> <type> <data>
 Options:
 -q, --quiet - only print error messages.
 -d, --debug - print debug output
+-R, --retry - retry failed connection attempts, if failure due to curl transient network errors
+-E ERRS, --error-codes ERRS
+            - comma-delimited error codes that will allow --retry (default "5,6,7")
+-D INT, --delay INT
+            - pause (in seconds) between --retry attempts, 0 means instantly (default 30)
+-T INT, --retry-times INT
+            - number of times to --retry, 0 means non-stop (default 0)

 Actions:
 ...
```

**Comment by fbartels** [comment]
hm.. adding that many optional parameters then also would call for switching to getops. The approach I had in mind would be to simply define some new default variables that can be overriden in `.config/pushbullet` (just like your curl options). By default the script could fail on the obvious connection errors (5,6,7 just like above) and retry every 60 seconds for at least five times.

**Comment by r2evans** [comment]
No need for `getopts` (which would subsequently break the POSIX-compliant shell PR just merged).

With the assumption that variable arguments are placed *before* "action", it's easy enough to use something like (untested):

```sh
PARSEARGS=1
while [ -n "${PARSEARGS}" && "$#" -gt "0" ]; do
    case "$1" in
        -R|--retry)
            DORETRY=1
            ;;
        -E|--retry-errors)
            shift
            ERRCODES=$1
            ;;
        -T|--retry-times)
            shift
            RETRYTIMES=$1
            ;;
        -D|--retry-delay)
            shift
            RETRYDELAY=$1
            ;;
        --force-short-delay)
            RETRYDELAYSHORT=1
            ;;
        *)
            unset PARSEARGS
            ;;
    esac
    if [ -n "${PARSEARGS}" ]; then shift ; fi
done
```

In general I like the thought of storing defaults in `~/.config/pushbullet`, though we need to make sure that the arguments allow "easily disabling the default"; for example, if the default is (say) `-T 2`, then using `-T 0` should ensure no retries are attempted.

**Comment by r2evans** [comment]
Let's continue this conversation in #83.
