### ISSUE TITLE
Question: Sending note to contacts ( not device )

### ISSUE THREAD

**Issue by ajkis** [Red5d/pushbullet-bash#91]
Is there a way to send note to contact.

**Comment by ajkis** [comment]
It seems its just sending email 
```
/opt/pushbullet-bash/pushbullet push contact@gmail.com note "test"
Sending to email address ales.ru7ar@gmail.com
```
the user is in my Chats/Contacts: list if i check with pushbullet list

**Comment by fbartels** [comment]
the output you have posted indicates that he is indeed sending a note (contacts are identified by their email if I remember correctly and pushbullet will only actually send an email if the contact does not exist). don't these messages show up in pushbullet?

https://github.com/Red5d/pushbullet-bash/blob/master/pushbullet#L548-L550

The only thing that wonders me are the differing email addresses. an incomplete attempt at hiding your real address?

**Comment by ajkis** [comment]
yea i copy pasted to fast wanted to remove my friends email address. 

The list command shows my contacts, I only wonder if there is a way to create a device from contact

**Comment by fbartels** [comment]
> I only wonder if there is a way to create a device from contact

no that is not possible with the api of pushbullet. devices are your own and contacts are external.
